### ISSUE TITLE
References and final proof read

### ISSUE THREAD

**Issue by matthewjay15** [UCL-ECHILD/docs.echild.ac.uk-website#22]
The references (i.e. the bibilographic references) need checking and updating throughout.  I also have not yet done a proper proof read.

**Comment by tony-stone** [comment]
Essentially all the references should already be listed in [web_source/references.bib](https://github.com/UCL-ECHILD/docs.echild.ac.uk-website/blob/eeaa812167dca861b5609d2cd8c8fae89daef676/web_source/references.bib#L1) but they have not actually been referenced within the various pages using the `[@ref_id]` notation. The `ref_id` is the bit after the open curly bracket on the top line of each bibtex entry, e.g. the id of the first reference in the references file is _echild2023a_, so that would be `[@echild2023a]`.

You can use multiple citations in the same place by separating them with semicolons, e.g. `[@education2019a; @jay2019a]`.

Probably the easiest to find improperly cited references is to "Find in Files..." (if using RStudio) the following regular expression:
`\[[0-9]+(\]|\-|,)`. (Since the text was copied from the pdf ECHILD User guide in which references are formatted `[N]` or `[N-N]` or `[N, N]` (where `N` is one or more digit), etc. that regular expression should work.)

Thanks

**Comment by matthewjay15** [comment]
Working on this now.
Also, ref 2 leads to a 404, should be replaced with https://www.adruk.org/our-work/browse-all-projects/echild-linking-childrens-health-and-education-data-for-england-142/

**Comment by matthewjay15** [comment]
Also need to fix links to NHSE datasets that currently point to old versions on https://web.www.healthdatagateway.org/

**Comment by matthewjay15** [comment]
Pull request sent to fix all of above

**Comment by matthewjay15** [comment]
New update fixes commas
